const html = `<!DOCTYPE html>
<script>
const name = "Leonoor";
const quote = "Success is not a destination; it is a journey we must constantly pursue.";
</script>
<script src="index.js"></script>
<body>
  <h1>Hello World</h1>
  <p>This markup was generated by a Cloudflare Worker. And here is a change!</p>
</body>`;

const name1 = "Leonoor";
const quote = "Success is not a destination; it is a journey we must constantly pursue.";

async function handleRequest(request) {
  return new Response(html, {
    headers: {
      'content-type': 'text/html;charset=UTF-8',
      'set-cookie': quote,
      'set-cookie': name1,
    },
  });
}

addEventListener('fetch', event => {
  return event.respondWith(handleRequest(event.request));
});
